name: Flutter Deployment - Referral_N_Earn (develop)

on:
  push:
    branches: [ main ]
 
jobs:
 build:
   name: Build & Release
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --release --split-per-abi
      - name: Deploy to my s3 bucket
        uses: actions/upload-artifact@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_EC2_SSH_KEY }}
          SOURCE: "/home/ubuntu/build/app/outputs/apk/release/*"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          
         
         
         
        
        
        
        
        
        
        
        
        
        
      
