name: Flutter Deployment - Referral_N_Earn (develop)

on:
  push:
    branches: [ main ]
 
jobs:
 build:
   name: Flutter Deployment
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - name: Build    
      - run: flutter build apk --release --split-per-abi
      - uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-south-1
      - name: Deploy
        run: aws s3 sync ./build/app/outputs/flutter-apk/ s3://fluter 
